// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiB1fy2Hh6Yq6lUTGtMBV3h5JM1C4ew7Q',
    appId: '1:617538271214:web:6b205d5233687371af80ff',
    messagingSenderId: '617538271214',
    projectId: 'edupay-a5f33',
    authDomain: 'edupay-a5f33.firebaseapp.com',
    storageBucket: 'edupay-a5f33.appspot.com',
    measurementId: 'G-0VL6PFHB6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgwUIUFcxkCes7BMMq26wKpCKPDmxfi9Y',
    appId: '1:617538271214:android:30ca6276a14fe142af80ff',
    messagingSenderId: '617538271214',
    projectId: 'edupay-a5f33',
    storageBucket: 'edupay-a5f33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTJ-B5Yxc9ctPwhCIBInVLNPJRAQfu4x8',
    appId: '1:617538271214:ios:5f5c44dae9c0a115af80ff',
    messagingSenderId: '617538271214',
    projectId: 'edupay-a5f33',
    storageBucket: 'edupay-a5f33.appspot.com',
    iosBundleId: 'com.hdg.edupay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiB1fy2Hh6Yq6lUTGtMBV3h5JM1C4ew7Q',
    appId: '1:617538271214:web:bc7f888a966ea617af80ff',
    messagingSenderId: '617538271214',
    projectId: 'edupay-a5f33',
    authDomain: 'edupay-a5f33.firebaseapp.com',
    storageBucket: 'edupay-a5f33.appspot.com',
    measurementId: 'G-Z1XN06PJGN',
  );
}